"""
Android Security Tools Module
"""

import os
import zipfile
import xml.etree.ElementTree as ET
from colorama import Fore, Style
import hashlib

class AndroidSecurity:
    """Android Security Analysis Tools"""
    
    @staticmethod
    def apk_analyzer(apk_path):
        """Analyze APK file"""
        print(f"\n{Fore.CYAN}[*] Analyzing APK: {apk_path}{Style.RESET_ALL}\n")
        
        if not os.path.exists(apk_path):
            print(f"{Fore.RED}[!] APK file not found!{Style.RESET_ALL}")
            return
        
        try:
            # Calculate file hash
            with open(apk_path, 'rb') as f:
                file_hash = hashlib.sha256(f.read()).hexdigest()
            
            print(f"{Fore.GREEN}[+] File Hash (SHA256):{Style.RESET_ALL} {file_hash}")
            print(f"{Fore.GREEN}[+] File Size:{Style.RESET_ALL} {os.path.getsize(apk_path)} bytes")
            
            # Extract APK
            with zipfile.ZipFile(apk_path, 'r') as zip_ref:
                # List files
                files = zip_ref.namelist()
                print(f"\n{Fore.YELLOW}[*] APK Contents:{Style.RESET_ALL}")
                print(f"  - Total files: {len(files)}")
                
                # Check for AndroidManifest.xml
                if 'AndroidManifest.xml' in files:
                    print(f"{Fore.GREEN}  ✓ AndroidManifest.xml found{Style.RESET_ALL}")
                
                # Check for classes.dex
                dex_files = [f for f in files if f.endswith('.dex')]
                print(f"  - DEX files: {len(dex_files)}")
                
                # Check for native libraries
                lib_files = [f for f in files if 'lib/' in f]
                if lib_files:
                    print(f"  - Native libraries: {len(lib_files)}")
                    architectures = set([f.split('/')[1] for f in lib_files if len(f.split('/')) > 1])
                    print(f"  - Architectures: {', '.join(architectures)}")
                
                # Check for resources
                res_files = [f for f in files if f.startswith('res/')]
                print(f"  - Resource files: {len(res_files)}")
                
                # Security checks
                print(f"\n{Fore.YELLOW}[*] Security Analysis:{Style.RESET_ALL}")
                
                # Check for common security files
                if 'META-INF/CERT.RSA' in files or 'META-INF/CERT.DSA' in files:
                    print(f"{Fore.GREEN}  ✓ APK is signed{Style.RESET_ALL}")
                else:
                    print(f"{Fore.RED}  ✗ APK is not signed{Style.RESET_ALL}")
                
                # Check for ProGuard
                if 'proguard-project.txt' in files or any('proguard' in f.lower() for f in files):
                    print(f"{Fore.GREEN}  ✓ ProGuard configuration found{Style.RESET_ALL}")
                else:
                    print(f"{Fore.YELLOW}  ! No ProGuard configuration detected{Style.RESET_ALL}")
                
                print(f"\n{Fore.GREEN}[+] Analysis complete!{Style.RESET_ALL}\n")
                
        except Exception as e:
            print(f"{Fore.RED}[!] Error analyzing APK: {e}{Style.RESET_ALL}")
    
    @staticmethod
    def proguard_generator():
        """Generate ProGuard configuration"""
        print(f"\n{Fore.CYAN}[*] ProGuard Configuration Generator{Style.RESET_ALL}\n")
        
        config = """# ProGuard Configuration
# Generated by SecToolkit

# Keep source file names and line numbers for debugging
-keepattributes SourceFile,LineNumberTable

# Keep annotations
-keepattributes *Annotation*

# Keep generic signatures
-keepattributes Signature

# Keep exceptions
-keepattributes Exceptions

# Keep inner classes
-keepattributes InnerClasses

# Keep native methods
-keepclasseswithmembernames class * {
    native <methods>;
}

# Keep custom views
-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet);
}

# Keep enums
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# Keep Parcelable
-keepclassmembers class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}

# Keep Serializable
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

# Optimization
-optimizationpasses 5
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-verbose

# Remove logging
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** v(...);
    public static *** i(...);
}
"""
        
        output_file = "proguard-rules.pro"
        with open(output_file, 'w') as f:
            f.write(config)
        
        print(f"{Fore.GREEN}[+] ProGuard configuration saved to: {output_file}{Style.RESET_ALL}")
        print(f"\n{Fore.YELLOW}[*] Add this to your build.gradle:{Style.RESET_ALL}")
        print("""
android {
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
""")
    
    @staticmethod
    def security_checker(apk_path):
        """Check APK for common security issues"""
        print(f"\n{Fore.CYAN}[*] Security Checker{Style.RESET_ALL}\n")
        print(f"{Fore.YELLOW}[*] Checking: {apk_path}{Style.RESET_ALL}\n")
        
        if not os.path.exists(apk_path):
            print(f"{Fore.RED}[!] APK file not found!{Style.RESET_ALL}")
            return
        
        issues = []
        
        try:
            with zipfile.ZipFile(apk_path, 'r') as zip_ref:
                files = zip_ref.namelist()
                
                # Check 1: Unsigned APK
                if not any('META-INF/CERT' in f for f in files):
                    issues.append(("HIGH", "APK is not signed"))
                
                # Check 2: Debuggable
                # Note: Would need to parse AndroidManifest.xml properly
                
                # Check 3: Backup allowed
                # Note: Would need to parse AndroidManifest.xml properly
                
                # Check 4: Clear text traffic
                # Note: Would need to parse network security config
                
                # Check 5: Hardcoded secrets (basic check)
                for file in files:
                    if file.endswith('.xml') or file.endswith('.json'):
                        try:
                            content = zip_ref.read(file).decode('utf-8', errors='ignore')
                            if 'password' in content.lower() or 'api_key' in content.lower():
                                issues.append(("MEDIUM", f"Potential hardcoded secrets in {file}"))
                        except:
                            pass
                
                # Display results
                if issues:
                    print(f"{Fore.RED}[!] Security Issues Found:{Style.RESET_ALL}\n")
                    for severity, issue in issues:
                        color = Fore.RED if severity == "HIGH" else Fore.YELLOW
                        print(f"{color}  [{severity}] {issue}{Style.RESET_ALL}")
                else:
                    print(f"{Fore.GREEN}[+] No obvious security issues found!{Style.RESET_ALL}")
                
                print(f"\n{Fore.YELLOW}[*] Note: This is a basic check. Use professional tools for comprehensive analysis.{Style.RESET_ALL}\n")
                
        except Exception as e:
            print(f"{Fore.RED}[!] Error: {e}{Style.RESET_ALL}")
    
    @staticmethod
    def certificate_validator(apk_path):
        """Validate APK certificate"""
        print(f"\n{Fore.CYAN}[*] Certificate Validator{Style.RESET_ALL}\n")
        print(f"{Fore.YELLOW}[*] Checking: {apk_path}{Style.RESET_ALL}\n")
        
        if not os.path.exists(apk_path):
            print(f"{Fore.RED}[!] APK file not found!{Style.RESET_ALL}")
            return
        
        try:
            with zipfile.ZipFile(apk_path, 'r') as zip_ref:
                files = zip_ref.namelist()
                
                # Find certificate files
                cert_files = [f for f in files if 'META-INF/' in f and ('.RSA' in f or '.DSA' in f)]
                
                if cert_files:
                    print(f"{Fore.GREEN}[+] Certificate files found:{Style.RESET_ALL}")
                    for cert in cert_files:
                        print(f"  - {cert}")
                    
                    # Extract and analyze certificate
                    # Note: Would need pyOpenSSL or cryptography for full analysis
                    print(f"\n{Fore.YELLOW}[*] Use 'keytool' or 'apksigner' for detailed certificate info:{Style.RESET_ALL}")
                    print(f"  keytool -printcert -jarfile {apk_path}")
                    print(f"  apksigner verify --print-certs {apk_path}")
                else:
                    print(f"{Fore.RED}[!] No certificate files found - APK is unsigned!{Style.RESET_ALL}")
                
        except Exception as e:
            print(f"{Fore.RED}[!] Error: {e}{Style.RESET_ALL}")
    
    @staticmethod
    def handle_choice(choice):
        """Handle menu choice"""
        if choice == '0':
            return
        elif choice == '1':
            apk_path = input(f"{Fore.CYAN}[>] Enter APK path: {Style.RESET_ALL}").strip()
            AndroidSecurity.apk_analyzer(apk_path)
        elif choice == '2':
            AndroidSecurity.proguard_generator()
        elif choice == '3':
            apk_path = input(f"{Fore.CYAN}[>] Enter APK path: {Style.RESET_ALL}").strip()
            AndroidSecurity.security_checker(apk_path)
        elif choice == '4':
            apk_path = input(f"{Fore.CYAN}[>] Enter APK path: {Style.RESET_ALL}").strip()
            AndroidSecurity.certificate_validator(apk_path)
        else:
            print(f"{Fore.RED}[!] Invalid choice!{Style.RESET_ALL}")
        
        input(f"\n{Fore.YELLOW}Press Enter to continue...{Style.RESET_ALL}")
