"""
Development Tools Module
"""

import os
import json
from colorama import Fore, Style
from datetime import datetime

class DevTools:
    """Development Tools"""
    
    @staticmethod
    def build_automation():
        """Build automation helper"""
        print(f"\n{Fore.CYAN}[*] Build Automation Helper{Style.RESET_ALL}\n")
        print(f"{Fore.YELLOW}[*] Generate build script for Android project{Style.RESET_ALL}\n")
        
        project_name = input(f"{Fore.CYAN}[>] Project name: {Style.RESET_ALL}").strip()
        build_type = input(f"{Fore.CYAN}[>] Build type (debug/release): {Style.RESET_ALL}").strip().lower() or "release"
        
        script = f"""#!/bin/bash
# Build Automation Script for {project_name}
# Generated by SecToolkit

echo "Building {project_name}..."

# Clean previous builds
./gradlew clean

# Build APK
./gradlew assemble{build_type.capitalize()}

# Check if build was successful
if [ $? -eq 0 ]; then
    echo "Build successful!"
    
    # Find APK
    APK_PATH=$(find app/build/outputs/apk/{build_type} -name "*.apk" | head -n 1)
    
    if [ -n "$APK_PATH" ]; then
        echo "APK location: $APK_PATH"
        
        # Calculate hash
        echo "SHA256: $(sha256sum "$APK_PATH" | cut -d' ' -f1)"
        
        # Get APK size
        echo "Size: $(du -h "$APK_PATH" | cut -f1)"
    fi
else
    echo "Build failed!"
    exit 1
fi
"""
        
        filename = f"build_{project_name.lower().replace(' ', '_')}.sh"
        with open(filename, 'w') as f:
            f.write(script)
        
        # Make executable
        os.chmod(filename, 0o755)
        
        print(f"{Fore.GREEN}[+] Build script saved to: {filename}{Style.RESET_ALL}")
        print(f"{Fore.YELLOW}[*] Run with: ./{filename}{Style.RESET_ALL}\n")
    
    @staticmethod
    def version_manager():
        """Version management tool"""
        print(f"\n{Fore.CYAN}[*] Version Manager{Style.RESET_ALL}\n")
        
        version_file = "version.json"
        
        if os.path.exists(version_file):
            with open(version_file, 'r') as f:
                version_data = json.load(f)
        else:
            version_data = {
                "major": 1,
                "minor": 0,
                "patch": 0,
                "build": 0,
                "history": []
            }
        
        current_version = f"{version_data['major']}.{version_data['minor']}.{version_data['patch']}"
        
        print(f"{Fore.GREEN}[+] Current Version: {current_version} (Build {version_data['build']}){Style.RESET_ALL}\n")
        
        print(f"{Fore.YELLOW}[*] Update version:{Style.RESET_ALL}")
        print(f"1. Major (breaking changes)")
        print(f"2. Minor (new features)")
        print(f"3. Patch (bug fixes)")
        print(f"4. Build number only\n")
        
        choice = input(f"{Fore.CYAN}[>] Choose update type: {Style.RESET_ALL}").strip()
        
        if choice == '1':
            version_data['major'] += 1
            version_data['minor'] = 0
            version_data['patch'] = 0
        elif choice == '2':
            version_data['minor'] += 1
            version_data['patch'] = 0
        elif choice == '3':
            version_data['patch'] += 1
        elif choice == '4':
            pass
        else:
            print(f"{Fore.RED}[!] Invalid choice{Style.RESET_ALL}")
            return
        
        version_data['build'] += 1
        
        # Add to history
        new_version = f"{version_data['major']}.{version_data['minor']}.{version_data['patch']}"
        notes = input(f"{Fore.CYAN}[>] Release notes: {Style.RESET_ALL}").strip()
        
        version_data['history'].append({
            "version": new_version,
            "build": version_data['build'],
            "date": datetime.now().isoformat(),
            "notes": notes
        })
        
        # Save
        with open(version_file, 'w') as f:
            json.dump(version_data, f, indent=2)
        
        print(f"\n{Fore.GREEN}[+] Version updated to: {new_version} (Build {version_data['build']}){Style.RESET_ALL}\n")
        
        # Show recent history
        print(f"{Fore.YELLOW}[*] Recent versions:{Style.RESET_ALL}")
        for entry in version_data['history'][-5:]:
            print(f"  {entry['version']} (Build {entry['build']}) - {entry['date'][:10]}")
            print(f"    {entry['notes']}")
        print()
    
    @staticmethod
    def dependency_checker():
        """Check for outdated dependencies"""
        print(f"\n{Fore.CYAN}[*] Dependency Checker{Style.RESET_ALL}\n")
        print(f"{Fore.YELLOW}[*] Checking build.gradle for dependencies...{Style.RESET_ALL}\n")
        
        gradle_file = input(f"{Fore.CYAN}[>] Path to build.gradle (default: build.gradle): {Style.RESET_ALL}").strip() or "build.gradle"
        
        if not os.path.exists(gradle_file):
            print(f"{Fore.RED}[!] File not found!{Style.RESET_ALL}")
            return
        
        try:
            with open(gradle_file, 'r') as f:
                content = f.read()
            
            # Find dependencies
            import re
            dependencies = re.findall(r'implementation\s+["\']([^"\']+)["\']', content)
            
            if dependencies:
                print(f"{Fore.GREEN}[+] Found {len(dependencies)} dependencies:{Style.RESET_ALL}\n")
                for dep in dependencies:
                    print(f"  - {dep}")
                
                print(f"\n{Fore.YELLOW}[*] To check for updates, use:{Style.RESET_ALL}")
                print(f"  ./gradlew dependencyUpdates")
                print(f"\n{Fore.YELLOW}[*] Or add this plugin to build.gradle:{Style.RESET_ALL}")
                print(f"  id 'com.github.ben-manes.versions' version '0.42.0'")
            else:
                print(f"{Fore.YELLOW}[*] No dependencies found{Style.RESET_ALL}")
            
            print()
            
        except Exception as e:
            print(f"{Fore.RED}[!] Error: {e}{Style.RESET_ALL}")
    
    @staticmethod
    def code_quality_analyzer():
        """Analyze code quality"""
        print(f"\n{Fore.CYAN}[*] Code Quality Analyzer{Style.RESET_ALL}\n")
        
        project_dir = input(f"{Fore.CYAN}[>] Project directory (default: .): {Style.RESET_ALL}").strip() or "."
        
        if not os.path.exists(project_dir):
            print(f"{Fore.RED}[!] Directory not found!{Style.RESET_ALL}")
            return
        
        print(f"\n{Fore.YELLOW}[*] Analyzing project structure...{Style.RESET_ALL}\n")
        
        # Count files
        java_files = []
        kotlin_files = []
        xml_files = []
        
        for root, dirs, files in os.walk(project_dir):
            for file in files:
                if file.endswith('.java'):
                    java_files.append(os.path.join(root, file))
                elif file.endswith('.kt'):
                    kotlin_files.append(os.path.join(root, file))
                elif file.endswith('.xml'):
                    xml_files.append(os.path.join(root, file))
        
        print(f"{Fore.GREEN}[+] Project Statistics:{Style.RESET_ALL}\n")
        print(f"  Java files: {len(java_files)}")
        print(f"  Kotlin files: {len(kotlin_files)}")
        print(f"  XML files: {len(xml_files)}")
        
        # Count lines
        total_lines = 0
        for file_list in [java_files, kotlin_files]:
            for file in file_list:
                try:
                    with open(file, 'r', encoding='utf-8', errors='ignore') as f:
                        total_lines += len(f.readlines())
                except:
                    pass
        
        print(f"  Total lines of code: {total_lines}")
        
        print(f"\n{Fore.YELLOW}[*] Recommended tools for detailed analysis:{Style.RESET_ALL}")
        print(f"  - Android Lint: ./gradlew lint")
        print(f"  - Detekt (Kotlin): https://detekt.dev")
        print(f"  - SonarQube: https://www.sonarqube.org")
        print(f"  - Checkstyle (Java): https://checkstyle.org")
        print()
    
    @staticmethod
    def handle_choice(choice):
        """Handle menu choice"""
        if choice == '0':
            return
        elif choice == '1':
            DevTools.build_automation()
        elif choice == '2':
            DevTools.version_manager()
        elif choice == '3':
            DevTools.dependency_checker()
        elif choice == '4':
            DevTools.code_quality_analyzer()
        else:
            print(f"{Fore.RED}[!] Invalid choice!{Style.RESET_ALL}")
        
        input(f"\n{Fore.YELLOW}Press Enter to continue...{Style.RESET_ALL}")
